apiVersion: webapp.ionos.com/v1
kind: Guestbook
metadata:
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/managed-by: kustomize
  name: guestbook-sample
spec:
  size: 3
  configMapName: guestbook
  type: Phone
  # TODO(user): Add fields here
